CONFIG_FILE_NAME = "config.json"
COIN_CONVERTER_PARAM_IDS = 'ids'
COIN_CONVERTER_VS_CURRENCY_PARAM = 'vs_currencies'

GOOGLE_CREDENTIALS_PATH = "google_credentials"
GOOGLE_TOKENS_PATH = "google_tokens"

TARGET_CURRENCY = 'TARGET_CURRENCY'

PRICE_URL_SECRET_NAME = 'COIN_PRICE_URL_SECRET_NAME'

DATETIME_FORMAT = '%m/%d/%Y %H:%M:%S'

SPREADSHEET_NAME = "SPREADSHEET_NAME"

TRACKER_SECRET_NAME = "CURRENCY_TRACKER_SECRET_NAME"

COIN_GECKO_SIMPLE_PRICE_API = "https://api.coingecko.com/api/v3/simple/price"


TARGET_CURRENCY_SECRET_NAME = "TARGET_CURRENCY_SECRET_NAME"

VALUEINPUTOPTION = "RAW"

SHEET_ = "Sheet1"

SPREADSHEET_ID_SECRET = "SPREADSHEET_ID_SECRET_NAME"

GOOGLE_BUILD_VERSION = "v4"

SERVICE_NAME = "sheets"

COIN_API_HEADERS = "COIN_API_HEADERS_SECRET_NAME"

CRED_FILE_SECRET_NAME = "CRED_FILE_SECRET_NAME"

TOKEN_FILE_SECRET_NAME = "TOKEN_FILE_SECRET_NAME"

GOOGLE_SCOPE_SECRET_NAME = "GOOGLE_SCOPE_SECRET_NAME"

